### ISSUE TITLE
iOS 18 doesn't support FreeBird

### ISSUE THREAD

**Issue by techdevmaestro** [nyathea/FreeBird#6]
Hey, 
I installed the FreeBird app without any problems but I can't open it because it's saying that "app needs to be updated"
My iPhone is on iOS 18.0 Dev Beta

**Comment by actuallyaridan** [comment]
I’m on 18.1 beta 2, no issues for me. How did you sideload it?

**Comment by techdevmaestro** [comment]
through apple configurator

**Comment by actuallyaridan** [comment]
Try using Sideloadly.

**Comment by techdevmaestro** [comment]
works like a charm thanks
