### ISSUE TITLE
Some issues and suggestions

### ISSUE THREAD

**Issue by bluz69** [nyathea/FreeBird#7]
When i open a twitter/x link it doesnt open freebird
It says that my notifications arent enabled but they are
the twitte logo is gray instead of blue
![IMG_2765](https://github.com/user-attachments/assets/13fe0fd6-a183-45aa-aabc-e4c97468f7e2)
![IMG_2767](https://github.com/user-attachments/assets/8a7bf23d-93c1-445e-b81e-03d0fbbf7c39)

**Comment by actuallyaridan** [comment]
Notifications don’t work because you’re using a Free Apple Developer account to sideload it. It’s not an issue with the app.

**Comment by bluz69** [comment]
oh okay i didnt know
